[package]
name = "actix-files"
version = "0.6.0-beta.1"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Static file serving for Actix Web"
readme = "README.md"
keywords = ["actix", "http", "async", "futures"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-web.git"
documentation = "https://docs.rs/actix-files/"
categories = ["asynchronous", "web-programming::http-server"]
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
name = "actix_files"
path = "src/lib.rs"

[dependencies]
actix-web = { git = 'https://github.com/inq/actix-web.git', default-features = false }
actix-service = { git = 'https://github.com/inq/actix-net.git'}
bitflags = "1"
bytes = "1"
futures-core = { version = "0.3.7", default-features = false }
futures-util = { version = "0.3.7", default-features = false }
derive_more = "0.99.5"
log = "0.4"
mime = "0.3"
mime_guess = "2.0.1"
percent-encoding = "2.1"
v_htmlescape = "0.12"

[dev-dependencies]
actix-rt = { git = 'https://github.com/inq/actix-net.git'}
actix-web = { git = 'https://github.com/inq/actix-web.git'}
